typedef enum {
    TEA_CHAMBER_EMPTY,
    TEA_CHAMBER_REMOVE_WATER_FROM_CHAMBER,
    TEA_CHAMBER_TURN_ON_WATER_PUMP_SV,
    TEA_CHAMBER_WATER_FILLING,
    TEA_CHAMBER_WATER_TURN_OFF_WATER_PUMP_AND_SV,
    TEA_CHAMBER_WAIT_TIME_FOR_LEAD_SCREW_TO_MOVE_DOWN,
    TEA_CHAMBER_POWDER_AND_WATER_ADDING,
    TEA_CHAMBER_DECOTION_PREPARATION,
    TEA_CHAMBER_DECOTION_READY,
    TEA_CHAMBER_TURN_ON_ST_INLET_SV,
    TEA_CHAMBER_OVERALL_TEA_DESPENSING,
    TEA_CHAMBER_REMOVE_TEA_POWDER_WASTAGE,
    TEA_CHAMBER_TEA_PREPARATION_PROCESS_FAILED,
} Tea_Preparation_Process_State_t;

Tea_Preparation_Process_State_t tea_process_state = TEA_CHAMBER_EMPTY;


typedef enum{
  LEAD_SCREW_OFF,
  LEAD_SCREW_BOTTOM_TO_TOP,
  LEAD_SCREW_NUT_ROTATE_AT_TOP,
  LEAD_SCREW_NUT_ROTATING_BACKWARD,
  LEAD_SCREW_NUT_ROTATING_FORWARD,
  LEAD_SCREW_TOP_TO_BOTTOM,
  LEAD_SCREW_TOP,
  LEAD_SCREW_BOTTOM,
  LEAD_SCREW_DRIVE_IN_FAILED,
}lead_screw_drive_t;

lead_screw_drive_t lead_screw_drive = LEAD_SCREW_OFF;


typedef enum {
  TEA_FULL_CYCLE_PROCESS_START = 10,
  TEA_FULL_CYCLE_TEA_DESPENSING_IN_TO_ST_INLEL,
  TEA_FULL_CYCLE_TEA_OVERALL_DESPENSING_TO_ST,
  TEA_FULL_CYCLE_TEA_DESPENSING_OUT,
  TEA_FULL_CYCLE_TEA_OVERALL_DESPENSING_OUT,
  TEA_FULL_CYCLE_TURN_ON_PT_TANK_SV,
  TEA_FULL_CYCLE_WATER_ADDING,
  TEA_FULL_CYCLE_WATER_HEATING,
  TEA_FULL_CYCLE_WATER_DESPENSING_TO_ST,
  TEA_FULL_CYCLE_OVER_ALL_WATER_DESPENSING_WATER_TO_ST_CHAMBER,
  TEA_FULL_CYCLE_WATER_DESPENSING_OUT,
  TEA_FULL_CYCLE_OVER_ALL_WATER_DESPENSING_WATER_FROM_ST_CHAMBER,
  TEA_FULL_CYCLE_PROCESS_FAILED,
}full_cycle_t;

full_cycle_t full_cycle = TEA_FULL_CYCLE_PROCESS_START;


typedef enum{
  STORAGE_CHAMBER_TEA_LEVEL_CHECK_AND_TEMPERATURE_CHECK,
  STORAGE_CHAMBER_HEATER_ON,
  STORAGE_CHAMBER_CONSTANT_TEMPERATURE_MAINTAINCE,  
  STORAGE_CHAMBER_PROCESS_FAILED,
}storage_chamber_t;

storage_chamber_t storage_chamber = STORAGE_CHAMBER_TEA_LEVEL_CHECK_AND_TEMPERATURE_CHECK;

typedef enum {
  LEAD_SCREW_POSITION_NUT_TO_TOP,
  LEAD_SCREW_POSITION_UNKNOWN_AND_KNOWN,
  LEAD_SCREW_POSITION_NUT_TO_BOTTOM,
}lead_screw_position_t;

lead_screw_position_t lead_screw_position = LEAD_SCREW_POSITION_UNKNOWN_AND_KNOWN;



typedef enum {
  TEA = 1,
  MILLET,
  TEA_BAG_BOX,
  NO_REQUEST,
}request_t ;

request_t request = NO_REQUEST;


typedef enum {
  START_MORNING_SESSION_AFTER_POWER_LOSS = 0,
  START_AFTERNOON_SESSION_AFTER_POWER_LOSS,
  START_EVENING_SESSION_AFTER_POWER_LOSS,
  IDLE,
}power_loss_Session_t;

power_loss_Session_t power_loss_Session = IDLE;


typedef enum{
  CHECKING_FOR_REQUEST,
  CHECKING_FOR_TEA_CUP_STOCK,
  LINEAR_ACTUATOR_MOVING_FOR_CUP_PLACEMENT,
  LINEAR_ACTUATOR_REST_POSITION,
  CHECKING_FOR_CUP_PLACEMENT,
  DESPENISNG_TEA_TO_CUP,
  SERVING_FAILED,
}serve_state_t;

serve_state_t serve_state = CHECKING_FOR_REQUEST;

typedef enum {
  NO_SESSION,
  MORNING_CLEANING_SESSION_AND_TEA_PREPARATION_SESSION,
  AFTERNOON_CLEANING_SESSION_AND_TEA_PREPARATION_SESSION,
  EVENING_CLEANING_SESSION_AND_TEA_PREPARATION_SESSION,
  NIGHT_CLEANING_SESSION,
  RESET_CLEANING_SESSION,
}session_t;

session_t session = NO_SESSION;

